# Conexión a la base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/asr_agricola?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true
spring.datasource.username=asr_admin
spring.datasource.password=root

# Hibernate (ORM) - Actualiza las tablas automáticamente basándose en tus clases
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuración del servidor
server.port=8080